// Login
export const INICIAR_SESION = 'INICIAR_SESION';
export const INICIAR_SESION_EXITO = 'INICIAR_SESION_EXITO';
export const INICIAR_SESION_ERROR = 'INICIAR_SESION_ERROR';
export const LOGOUT = 'LOGOUT';
export const CLEAN_MESSAGE = 'CLEAN_MESSAGE';
export const USUARIO_AUTENTICADO_ERROR = 'USUARIO_AUTENTICADO_ERROR';

// User
export const ALL_LIST_USERS_EXITO = 'ALL_LIST_USERS_EXITO';
export const ALL_LIST_USERS_ERROR = 'ALL_LIST_USERS_ERROR';
export const DETAIL_USER_EXITO = 'DETAIL_USER_EXITO';
export const DETAIL_USER_ERROR = 'DETAIL_USER_ERROR';
export const UPDATE_USER_EXITO = 'UPDATE_USER_EXITO';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const DELETE_USER_EXITO = 'DELETE_USER_EXITO';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';
export const RESTART_STATUS_DELETE = 'RESTART_STATUS_DELETE';
export const CLEAN_USER_SELECTED = 'CLEAN_USER_SELECTED';